- name: Install Flatpak
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
