VERSION 0.7

FROM ubuntu:23.10

build:
  DO ../shared+BUILD
  DO ../shared+RUN_ANSIBLE_SCRIPT --tags=bun,node-js
  DO ../shared+CONFIG
  ENTRYPOINT ["bash"]
  SAVE IMAGE --push ghcr.io/hendric-dev/devcontainer/typescript
