- name: Install Helm for Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Helm for OpenSUSE
  import_tasks: suse.yml
  when: ansible_facts['os_family'] == 'Suse'
