- import_tasks: ../shared/tasks/import-os-specific-vars.yml

- name: Install Ruby system dependencies
  become: true
  ansible.builtin.package:
    name: "{{ libyaml_package_name }}"
    state: present

- name: Install rbenv
  become: true
  ansible.builtin.package:
    name: rbenv
    state: present

- name: Add rbenv init to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: 'eval "$(rbenv init - bash)"'
    state: present
    insertafter: EOF

- name: Clone the ruby-build repository
  ansible.builtin.git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install latest Ruby version
  shell: |
    ruby_version=$(rbenv install -l | grep -v - | tail -1)
    rbenv install $ruby_version --skip-existing
    rbenv global $ruby_version

- name: Install latest available Bundler Gem
  community.general.gem:
    name: bundler
    state: latest

- name: Install latest available Solargraph Gem
  community.general.gem:
    name: solargraph
    state: latest
