- name: Download Jsonnet binary
  become: true
  get_url:
    url: https://github.com/jsonnet-bundler/jsonnet-bundler/releases/latest/download/jb-linux-amd64
    dest: /usr/local/bin/jb
    mode: 0711
