- name: Install Oracle Instant Client dependencies
  become: true
  ansible.builtin.package:
    name: libaio1
    state: present

- name: Create oracle folder in home directory
  ansible.builtin.file:
    path: ~/oracle
    state: directory
    mode: "0755"

- name: Download Oracle Instant Client
  ansible.builtin.unarchive:
    src: https://download.oracle.com/otn_software/linux/instantclient/2110000/instantclient-basic-linux.x64-21.10.0.0.0dbru.zip
    dest: ~/oracle
    remote_src: yes

- name: Download Oracle Instant Client SDK
  ansible.builtin.unarchive:
    src: https://download.oracle.com/otn_software/linux/instantclient/2110000/instantclient-sdk-linux.x64-21.10.0.0.0dbru.zip
    dest: ~/oracle
    remote_src: yes

- name: Set LD_LIBRARY_PATH environment variable
  ansible.builtin.lineinfile:
    dest: ~/.profile
    line: "export LD_LIBRARY_PATH=$HOME/oracle/instantclient_21_10"
    state: present
    insertafter: EOF

- name: Add Oracle Instant Client to PATH
  ansible.builtin.lineinfile:
    dest: ~/.profile
    line: "export PATH=$PATH:$HOME/oracle/instantclient_21_10"
    state: present
    insertafter: EOF
