VERSION 0.7

FROM ubuntu:23.04

build:
  DO ../shared+BUILD
  DO +BUILD
  DO ../shared+CONFIG
  ENTRYPOINT ["bash", "-l"]
  SAVE IMAGE --push ghcr.io/hendric-dev/devcontainer/rust

BUILD:
  COMMAND
  DO ../shared+RUN_ANSIBLE_SCRIPT --tags=rust
