VERSION 0.6

FROM ubuntu:22.04

build:
  DO ../shared+BUILD
  DO +BUILD
  DO ../shared+CONFIG
  ENTRYPOINT ["bash"]
  SAVE IMAGE --push ghcr.io/hendric-dev/devcontainer/rust

BUILD:
  COMMAND
  DO +RUST

RUST:
  COMMAND
  RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

SYSTEM_LIBRARIES:
  COMMAND
  RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
