VERSION 0.7

BUILD:
  COMMAND
  DO +USER
  DO +ANSIBLE
  COPY ../ansible+file/ansible $HOME/ansible
  DO +RUN_ANSIBLE_SCRIPT --tags=earthly,oh-my-bash

ANSIBLE:
  COMMAND
  RUN sudo apt-get update && \
      sudo apt-get install -y ansible && \
      sudo rm -rf /var/lib/apt/lists/*
  RUN ansible-galaxy collection install community.general
  ENV ANSIBLE_FORCE_COLOR=True

CONFIG:
  COMMAND
  COPY devcontainer.json .
  ARG config=$(cat devcontainer.json)
  LABEL devcontainer.metadata=$config

RUN_ANSIBLE_SCRIPT:
  COMMAND
  ARG tags
  RUN ansible-playbook $HOME/ansible/main.yml -i $HOME/ansible/inventory.yml --tags $tags

USER:
  COMMAND
  DO +USER_PREREQUISITES
  ENV USER=developer
  ENV HOME=/home/$USER
  RUN useradd --create-home --shell /bin/bash $USER && \
      usermod -aG sudo $USER && \
      echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
      chown -R $USER:$USER $HOME
  USER $USER
  WORKDIR $HOME

USER_PREREQUISITES:
  COMMAND
  ENV DEBIAN_FRONTEND=noninteractive
  ENV LANG=de_DE.UTF-8
  RUN apt-get update && \
      apt-get install -y locales sudo tzdata && \
      rm -rf /var/lib/apt/lists/*
  RUN locale-gen de_DE.UTF-8
