- name: Download Lapce binary
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/lapce/lapce/releases/latest/download/Lapce-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: --strip-components=1
