- name: Check if Volta is installed
  stat:
    path: ~/.volta/bin/volta
  register: volta

- name: Download Volta install script
  when: not volta.stat.exists
  get_url:
    url: https://get.volta.sh
    dest: ~/volta.sh
    mode: 0755

- name: Execute Volta install script
  when: not volta.stat.exists
  shell: ~/volta.sh

- name: Set VOLTA_HOME environment variable
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: 'export VOLTA_HOME=$HOME/.volta'
    state: present
    insertafter: EOF

- name: Add Volta to PATH
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: 'export PATH=$PATH:$HOME/.volta/bin'
    state: present
    insertafter: EOF

- name: Remove Volta install script
  when: not volta.stat.exists
  ansible.builtin.file:
    path: ~/volta.sh
    state: absent

- name: Install latest Node.js version
  when: not volta.stat.exists
  command: ~/.volta/bin/volta install node

- name: Install latest Yarn version
  when: not volta.stat.exists
  command: ~/.volta/bin/volta install yarn
